name: Manual Sqitch Deployment

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Sqitch target (e.g., db:pg://user@host/dbname)"
        required: true
        default: "db:pg://postgres@localhost/app_db"
      command:
        description: "Sqitch command to run (deploy, verify, revert, etc)"
        required: true
        default: "deploy"

jobs:
  sqitch:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqitch libpq-dev postgresql-client

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for DB..."
            sleep 2
          done

      - name: Run Sqitch command
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          echo "Running: sqitch ${{ github.event.inputs.command }} ${{ github.event.inputs.target }}"
          sqitch ${{ github.event.inputs.command }} ${{ github.event.inputs.target }
