- name: Run Sqitch
  working-directory: ./supa/sqitch
  env:
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    DB_NAME: ${{ secrets.DB_NAME }}
    DB_HOST: ${{ secrets.DB_HOST }}
  run: |
    set -e

    # Resolve IPv4 address from Supabase hostname
    IP=$(dig +short A "$DB_HOST" | head -n 1)

    if [ -z "$IP" ]; then
      echo "Failed to resolve IPv4 for $DB_HOST"
      exit 1
    fi

    TARGET="db:pg://$DB_USER:$DB_PASSWORD@$IP/$DB_NAME?host=$DB_HOST"

    echo "Using target: $TARGET"
    sqitch ${{ github.event.inputs.command }} "$TARGET"
